---
title: "Fiji Quakes"
author: "Fiona Spooner"
date: "10/10/2019"
output: html_document
---

Leaflet is a really good package for creating interactive maps. Here I've put together an example for visualising earthquake data from around Fiji.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(leaflet)
library(htmltools)
```


```{r}
data(quakes)
head(quakes)

pal <- colorNumeric(
  palette = "Reds",
  domain = quakes$mag)


leaflet(quakes) %>%  
  addProviderTiles("CartoDB.Positron") %>%
  setView(mean(quakes$long), mean(quakes$lat), zoom = 4)%>% 
  addCircleMarkers(lng=quakes$long, lat=quakes$lat,radius = 0.01*quakes$depth, 
                   color = ~pal(quakes$mag), stroke = FALSE, fillOpacity = 0.7) %>% 
   addLabelOnlyMarkers(~long, ~lat, label = as.character(paste("Magnitude: ",quakes$mag)))  #adding a pop up 


```


Lots of other basemaps available - http://leaflet-extras.github.io/leaflet-providers/preview/


```{r}
leaflet(quakes) %>%  
  addProviderTiles("Stamen.Watercolor") %>%
  setView(mean(quakes$long), mean(quakes$lat), zoom = 4)%>% 
  addCircleMarkers(lng=quakes$long, lat=quakes$lat,radius = 0.01*quakes$depth, 
                   color = ~pal(quakes$mag), stroke = FALSE, fillOpacity = 0.7) %>% 
   addLabelOnlyMarkers(~long, ~lat, label = as.character(paste("Magnitude: ",quakes$mag)))  #adding a pop up 



```

```{r}
leaflet(quakes) %>%  
  addProviderTiles("Esri.WorldImagery") %>%
  setView(mean(quakes$long), mean(quakes$lat), zoom = 4)%>% 
  addCircleMarkers(lng=quakes$long, lat=quakes$lat,radius = 0.01*quakes$depth, 
                   color = ~pal(quakes$mag), stroke = FALSE, fillOpacity = 0.7) %>% 
   addLabelOnlyMarkers(~long, ~lat, label = as.character(paste("Magnitude: ",quakes$mag)))  #adding a pop up 


```